### ISSUE TITLE
Can't  publish my contract on the europe3.test

### ISSUE THREAD

**Issue by Tyvain** [signum-network/signum-smartj#17]
Hello, 

when I try to publish my contract on the europe3.test network. I get an error.
I also get the same error if I try to publish CryptoBall (smartJ) with no code modification. Here is the error:

```
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
signumj.entity.response.http.BRSError: BRS returned error code 5: Invalid or not specified parameters
    at signumj.entity.response.http.BRSResponse.throwIfError(BRSResponse.java:22)
    at signumj.service.impl.HttpBurstNodeService.checkBrsResponse(HttpBurstNodeService.java:77)
```
![image](https://user-images.githubusercontent.com/7066226/154898850-9e61fad5-f221-4c0a-b316-56315816d1c4.png)

I can publish some other contracts (more simple code) : hello, always running etc..

My contract source is here:
https://github.com/Tyvain/signum-smartj/blob/master/src/main/java/bt/dapps/CryptoBlackJack

**Comment by frankTheTank72** [comment]
@jjos2372  will look into that

**Comment by frankTheTank72** [comment]
please try it again - we have a new release on the testnet now --> https://github.com/signum-network/signum-node/releases/tag/v3.4.0-alpha1

**Comment by jjos2372** [comment]
Just tested and it is now possible to publish this contract using https://europe3.testnet.signum.network/ as node (the fix is on the node code not on SmartJ).

**Comment by jjos2372** [comment]
We will have to revisit this, since the fix had some side effects on other functions.

**Comment by Tyvain** [comment]
I still have a problem:

```
signumj.entity.response.http.BRSError: BRS returned error code 5: Invalid or not specified parameters
	at signumj.entity.response.http.BRSResponse.throwIfError(BRSResponse.java:22)
	at signumj.service.impl.HttpBurstNodeService.checkBrsResponse(HttpBurstNodeService.java:77)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
	at io.reactivex.Observable.subscribe(Observable.java:12285)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:12285)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
-
```

![image](https://user-images.githubusercontent.com/7066226/155096509-abe6a37d-fbfa-4ead-a069-080030483b59.png)

**Comment by jjos2372** [comment]
Yes, you need to run your own testnet node with the latest version for this to work:
https://github.com/signum-network/signum-node/releases/tag/v3.4.0-alpha1

And then select the `http://localhost:6876` as the node. Or check if you can use a public node with this version, there is a list at https://testnet.explorer.signum.network/peers/

**Comment by Tyvain** [comment]
Still not working:
- [testnet.airdns.org:7100](https://testnet.explorer.signum.network/peer/testnet.airdns.org:7100) -> timeout
- [lmsi.club](https://testnet.explorer.signum.network/peer/lmsi.club) -> 404
Also tryied some others from the list without success.
![image](https://user-images.githubusercontent.com/7066226/155297676-39fbef1f-b68a-4fc5-b9d5-a0a6caf00b61.png)

```
> Task :CryptoBlackJack.main()
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
	at java.base/java.net.Socket.connect(Socket.java:603)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at signumj.service.impl.HttpBurstNodeService.lambda$new$0(HttpBurstNodeService.java:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
	at io.reactivex.Observable.subscribe(Observable.java:12285)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:12285)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by jjos2372** [comment]
That is because you are not using the testnet port `http://lmsi.club:6876` works here with this contract.
